### ISSUE TITLE
ray.config.js not being respected (intercept_console_log)

### ISSUE THREAD

**Issue by vesper8** [permafrost-dev/vue-ray#9]
Hello hello!

I wrote to you in the Slack channel regarding an issue I am having where every call to `console.log` is being sent to ray. This is very undesirable in my use-case and is essentially making vue-ray (which I otherwise love) unusable until this is resolved

I found on the `node-ray` package that you can specify a `ray.config.js` file inside the project root where you can add some settings such as `intercept_console_log: false` to circumvent this issue.

I tried that but it seems like this doesn't work with `vue-ray`? I set it to false but it is still intercepting all `console.log` calls.

I then tried adding `interceptConsoleLog: false,` to the `vue-ray` config and this also doesn't work

It would be ncie if `interceptConsoleLog` was added as a configurable option for `vue-ray`

I hope this can be patched quickly as I look forward to being able to use `vue-ray` again soon

Please let me know if you need any more details. Many thanks!

**Comment by patinthehat** [comment]
@vesper8 This doesn't work with `vue-ray`. It doesn't have access to the file system, so config files can't be read.

I will add the `interceptConsoleLog` to the configuration options, stand by.

**Comment by patinthehat** [comment]
@vesper8 I've released version `1.17.0` which adds a `nodeRaySettings` configuration option - try something like the following:

```js
Vue.use(RayPlugin.default, {
  interceptErrors: true,
  showComponentEvents: [
    'created',
    'mounted',
  ],
  nodeRaySettings: {
    interceptConsoleLog: false,
  }
});
```

**Comment by vesper8** [comment]
@patinthehat I am currently on version `1.17.2`

But the above does not appear to be working at all

This is my Ray setup file:

```
import Vue from 'vue';

import { RayPlugin } from 'vue-ray/vue2';

Vue.use(RayPlugin, {
  interceptErrors: process.env.NODE_ENV === 'development',

  nodeRaySettings: {
    interceptConsoleLog: false,
  },

  host: process.env.NODE_ENV === 'development' ? 'localhost' : process.env.VUE_APP_RAY_URL_EXPOSE,
  scheme: process.env.NODE_ENV === 'development' ? 'http' : 'https',
  port: process.env.NODE_ENV === 'development' ? 23517 : 443,
  showComponentEvents: [
    // 'created',
    // 'mounted',
  ],
});
```

And yet all `console.log` calls are still being intercepted by Ray... I don't know what I'm doing wrong...

**Comment by vesper8** [comment]
@patinthehat Tried it again on a new project.. no matter what I do I can't make the console.log messages not go through Ray

I really hope you can resolve this soon, I know you took a stab at it but something tells me you didn't fully commit your solution code maybe?

While you're at it, it would be useful if you could specify which console messages can be intercepted by vue-ray.. there's `console.error`, `console.table`, `console.error`, `console.info`, `console.trace` and `console.debug`

**Comment by vesper8** [comment]
I know you must be super busy on something else @patinthehat. I look forward to being able to use ray on my remote projects without it intercepting console.log

Also, I'd like to be able to interceptErrors but also allow them to be sent to the debug console. Right now it intercepts and sends to ray and the console is empty. Sometimes my remote expose server fails or I forget that it's set to intercept all errors and I'm scratching my head because stuff is broken and I'm not seeing any red in my web console. It's nice to intercept but can you not completely capture the error and still allow it to be thrown in the console even if it's also sent to Ray?

**Comment by patinthehat** [comment]
My apologies @vesper8 - I lost track of this issue. I will give the `console.log` interception issue my full attention today.

As for intercepting errors but allowing them to pass through - I think it makes sense, but I need to put some thought into how best to add this to the configuration options.  Do you have any thoughts on that front?

**Comment by patinthehat** [comment]
@vesper8 I tracked down the issue with `console.log` interception being on by default and published v1.13.1 of `node-ray` - updating your deps should resolve the issue.

**Comment by vesper8** [comment]
> @vesper8 I tracked down the issue with `console.log` interception being on by default and published v1.13.1 of `node-ray` - updating your deps should resolve the issue.

Fantastic!! Thank you! I will test it and if I find any other issues I will report them back

> As for intercepting errors but allowing them to pass through

Honestly @patinthehat I don't think this requires an update to the configuration, this should simply be the default behaviour. If you opt to have Ray intercept the errors then it will do just that, intercept the error and send it to Ray.. there is no need to also specify whether you would want the error to still be outputted in the web console or not.. that should just be the default behaviour and I think that's what would be expected anyway. That's my opinion anyhow

**Comment by vesper8** [comment]
Happy to report that console.log is no longer being intercepted by default!

Similarly to above however, should I choose to turn on log interception, I would like to still continue to be output in the web console in that case, same as with errors.

I'm still unable to use your new callback features, as reported in the other opened issue

Adding
```
  sent_payload_callback: (rayInstance) => {
    // automatically make all payloads sent to Ray green.
    rayInstance.green();
  },

```

Caused a fatal error, and the other two options `enabled_callback` and `sending_payload_callback` seem to have no affect at all

**Comment by patinthehat** [comment]
@vesper8 I've updated the behavior of intercepting `console.log` calls to send the messages to both Ray and the console, and fixed the stack overflow when using `sent_payload_callback` in `node-ray` v1.14.0.  Please update your deps to resolve the issues. 

Thank you so much for the suggestions, bug reports, and your patience :smile:

**Comment by vesper8** [comment]
I'm sorry @patinthehat but it looks like it's still not working right.

After your changes, nothing I do can get vue-ray to intercept console.log anymore

I tried with

```
  nodeRaySettings: {
    interceptConsoleLog: true,
  },
```


With

```
  nodeRaySettings: {
    interceptConsoleLog: false,
  },
```

And without adding any `nodeRaySettings` at all. And no matter what I do I am no longer able to get ray to display any `console` calls

**Comment by patinthehat** [comment]
@vesper8 No apologies necessary, thank you for letting me know there's an issue.

Can you try the following in your init code and see if it enables the `console.log` interception?

```js
ray().interceptor().enable();
```

**Comment by patinthehat** [comment]
@vesper8 Please try updating to [`v1.17.3`](https://github.com/permafrost-dev/vue-ray/releases/tag/v1.17.3).  This should fix the issue; please let me know if you have any issues after updating.

**Comment by vesper8** [comment]
Thank you @patinthehat ! It's working now!

This is also work now:

```
  sent_payload_callback: (rayInstance) => {
    // automatically make all payloads sent to Ray green.
    rayInstance.green();
  },
```

But I still don't understand how to use

```
  enabled_callback: () => process.env.NODE_ENV === 'development',

  sending_payload_callback: (rayInstance, payloads) => {
    rayInstance.html('this is sent before every payload');
    if (payloads[0].getType() === 'custom') {
      payloads[0].data.content.content = 'payloads can be modified here';
    }
  },
```

Could you possibly include a small example of how this can be utilized?

Many thanks for the quick fix!

**Comment by patinthehat** [comment]
@vesper8 Glad to help - thanks again for letting me know that there was an issue :+1:  

Sending payloads from `sending_payload_callback` seems to be broken, so I'll have to take care of that.  Should be a quick fix - I'll try to get it published today.

Here's a short example for the callbacks and how to modify payloads:

```js
Ray.useDefaultSettings({
    nodeRaySettings: {
        interceptConsoleLog: true,
    },
    sent_payload_callback: ray => {
        ray.green();
    },
    sending_payload_callback: (ray, payloads) => {
        if (payloads[0].getType() === 'log') {
            if (payloads[0].values.length) {
                payloads[0].values[0] += ' - modified!';
            }
        }
    },
});
```

Then call `console.log` somewhere:

```js
console.log('hello world');
```

And hopefully you'll see the following in Ray:

![image](https://user-images.githubusercontent.com/5508707/120533689-02498d80-c3af-11eb-8100-7720ec00d01c.png)

**Comment by vesper8** [comment]
Hi @patinthehat,

Sorry to bring this up once again but it looks like the behaviour is changed again.. or maybe it wasn't completely fixed last time.. although I could have swore that it was.

Right now it appears that when I set use these settings:

```
Vue.use(RayPlugin, {
  interceptErrors: true,

  nodeRaySettings: {
    interceptConsoleLog: true,
  },
  ...
```

Then the errors are no longer being printed to my console and they are only sent to ray.

I would like it if the errors/console are always also sent to the debugger console no matter what. I thought this was working last time but today it seems to be gobbling up the errors and not sending them to the console anymore

**Comment by patinthehat** [comment]
Hey @vesper8 - thanks for letting me know.

Do you have a sample repository that replicates this issue that I can take a look at?

**Comment by vesper8** [comment]
Not at the moment no... I'll see if I can find the time to make one... but it won't be for at least a few days as I'm travelling at the moment.

**Comment by JoeriTheGreat** [comment]
> @vesper8 Glad to help - thanks again for letting me know that there was an issue 👍
> 
> Sending payloads from `sending_payload_callback` seems to be broken, so I'll have to take care of that. Should be a quick fix - I'll try to get it published today.
> 
> Here's a short example for the callbacks and how to modify payloads:
> 
> ```js
> Ray.useDefaultSettings({
>     nodeRaySettings: {
>         interceptConsoleLog: true,
>     },
>     sent_payload_callback: ray => {
>         ray.green();
>     },
>     sending_payload_callback: (ray, payloads) => {
>         if (payloads[0].getType() === 'log') {
>             if (payloads[0].values.length) {
>                 payloads[0].values[0] += ' - modified!';
>             }
>         }
>     },
> });
> ```
> 
> Then call `console.log` somewhere:
> 
> ```js
> console.log('hello world');
> ```
> 
> And hopefully you'll see the following in Ray:
> 
> ![image](https://user-images.githubusercontent.com/5508707/120533689-02498d80-c3af-11eb-8100-7720ec00d01c.png)

Is there a way to see the different type of payloads ?
